---
- name: Offensive Security Deployment
  hosts: localhost
  become: yes  # Use sudo for this playbook
  tasks:

    - name: Ensure git is installed
      apt:
        name: git
        state: present

    # Setup and file structure creation
    - name: Create a directory structure for organization
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /opt/web
        - /opt/windows
        - /opt/windows/compiled
        - /opt/wordlists
        - /opt/PSPY
        - /opt/network
        - /opt/reverse
        - /opt/cloud
        - /opt/rf-sdr
        - /opt/c2_frameworks
      tags: always

    # General Tools
    - name: Install general tools and compilers
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - golang-go
        - ruby
        - gcc
        - g++
        - clang
        - cmake
        - flameshot
        - python3-pip
        - pipx
        - python3-fuzzywuzzy
        - python3-pwntools
        - awscli
        - enum4linux-ng
        - docker.io
        - goshs
      tags: general

    # Windows tools
    - name: Install additional Windows tools via apt
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-impacket
        - evil-winrm
        - chisel
        - bloodhound
        - chisel
        - remmina
      tags: windows

    # Web tools
    - name: Install additional web tools via apt
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - burpsuite
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - feroxbuster
        - gobuster
        - ffuf
        - wfuzz
        - gospider
        - payloadsallthethings
      tags: web

    # Networking
    - name: Install network tools via apt
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - inetutils-traceroute
        - tor
        - sshuttle
      tags: network
      
    # RF/SDR Tools
    - name: Install RF/SDR tools via apt
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kali-tools-sdr
        - kali-tools-rfid
        - gnuradio
        - rtl-sdr
        - gqrx-sdr
        - airspy
        - soapysdr-tools
        - kalibrate-rtl
        - inspectrum
      tags: rf-sdr

    # Reverse Engineering Tools
    - name: Install reverse engineering tools via apt
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - libssl-dev
        - libffi-dev
        - build-essential
        - ltrace
        - edb-debugger
      tags: rev

    # Web Tools to /opt/web
    - name: Clone Web tools to /opt/web
      git:
        repo: "{{ item.repo }}"
        dest: "/opt/web/{{ item.name }}"
      loop:
        - {repo: 'https://github.com/MAWK0235/CVE-2024-24401.git', name: 'CVE-2024-24401-NAGIOS' }
        - { repo: 'https://github.com/MAWK0235/MinecraftLog4jAutoPwn.git', name: 'MinecraftLog4jAutoPWN' }
        - { repo: 'https://github.com/vladko312/SSTImap.git', name: 'SSTImap' }
        - { repo: 'https://github.com/enjoiz/XXEinjector.git', name: 'XXEInjector' }
        - { repo: 'https://github.com/nickpupp0/LogPoisoner.git', name: 'LogPoisoner' }
      tags: web
      ignore_errors: yes

     # Wordlists to /opt/wordlists/
    - name: Clone wordlist repositories to /opt/wordlists/
      git:
        repo: "{{ item.repo }}"
        dest: "/opt/wordlists/{{ item.name }}"
      loop:
        - { repo: 'https://github.com/swisskyrepo/PayloadsAllTheThings.git', name: 'PayloadsAllTheThings' }
        - { repo: 'https://github.com/trickest/wordlists.git', name: 'wordlists' }
        - { repo: 'https://github.com/insidetrust/statistically-likely-usernames.git', name: 'statistically-likely-usernames' }
        - { repo: 'https://github.com/NotSoSecure/password_cracking_rules.git', name: 'OneRuleToRuleThemAll'}
      tags: wordlists
      ignore_errors: yes
      
    # C2 Frameworks to /opt/c2_frameworks/
    - name: Clone c2 frameworks to /opt/c2_frameworks/
      get_url:
        url: "{{ item.url }}"
        dest: "/opt/c2_frameworks/{{ item.name }}"
      loop:
        - { url: 'https://github.com/BishopFox/sliver/releases/download/v1.5.42/sliver-client_linux', name: 'sliver-client_linux' }
        - { url: 'https://github.com/BishopFox/sliver/releases/download/v1.5.42/sliver-server_linux', name: 'sliver-server_linux' }
      tags: c2
      ignore_errors: yes

    # Pivoting Tools
    - name: Download pivoting tool release files to /opt/network/
      get_url:
        url: "{{ item.url }}"
        dest: "/opt/network/{{ item.filename }}"
      loop:
        - { url: 'https://github.com/nicocha30/ligolo-ng/releases/download/v0.6.2/ligolo-ng_agent_0.6.2_linux_amd64.tar.gz', filename: 'ligolo-ng_agent_0.6.2_linux_amd64.tar.gz' }
        - { url: 'https://github.com/nicocha30/ligolo-ng/releases/download/v0.6.2/ligolo-ng_proxy_0.6.2_linux_amd64.tar.gz', filename: 'ligolo-ng_proxy_0.6.2_linux_amd64.tar.gz' }
        - { url: 'https://github.com/jpillora/chisel/releases/download/v1.10.0/chisel_1.10.0_linux_amd64.gz', filename: 'chisel_1.10.0_linux_amd64.gz' }
        - { url: 'https://github.com/jpillora/chisel/releases/download/v1.10.0/chisel_1.10.0_windows_amd64.gz', filename: 'chisel_1.10.0_windows_amd64.gz' }
      tags: pivot
      ignore_errors: yes

    # Rev Eng
    - name: Clone reverse engineering tools to /opt/reverse/
      git:
        repo: "{{ item.repo }}"
        dest: "/opt/reverse/{{ item.name }}"
      loop:
        - { repo: 'https://github.com/radareorg/radare2.git', name: 'radare2' }
        - { repo: 'https://github.com/angr/angr.git', name: 'angr' }
      tags: rev
      ignore_errors: yes

    # Main
    - name: Clone general tools to /opt/
      git:
        repo: "{{ item.repo }}"
        dest: "/opt/{{ item.name }}"
      loop:
        - { repo: 'https://github.com/cnotin/SplunkWhisperer2.git', name: 'SplunkWhisperer2' }
        - { repo: 'https://github.com/carlospolop/PEASS-ng.git', name: 'PEASS-ng' }
        - { repo: 'https://github.com/MAWK0235/LinDistributor.git', name: 'LinDistrubutor.py'}
        - { repo: 'https://github.com/urbanadventurer/username-anarchy.git', name: 'username-anarchy' }
        - { repo: 'https://github.com/21y4d/nmapAutomator.git', name: 'nmapAutomator' }
        - { repo: 'https://github.com/GerbenJavado/LinkFinder.git', name: 'LinkFinder' }
        - { repo: 'https://github.com/Bashfuscator/Bashfuscator.git', name: 'bashfuscator' }
      tags: general
      ignore_errors: yes
    
    # GIT Windows Tools
    - name: Clone Windows tools repositories to /opt/windows/
      git:
        repo: "{{ item.repo }}"
        dest: "/opt/windows/{{ item.name }}"
      loop:
        - { repo: 'https://github.com/lgandx/Responder.git', name: 'Responder' }
        - { repo: 'https://github.com/ropnop/kerbrute.git', name: 'kerbrute' }
        - { repo: 'https://github.com/dirkjanm/krbrelayx.git', name: 'krbrelayx' }
        - { repo: 'https://github.com/andrew-d/static-binaries.git', name: 'static-binaries' }
        - { repo: 'https://github.com/topotam/PetitPotam.git', name: 'PetitPotam' }
        - { repo: 'https://github.com/wh0amitz/PetitPotato.git', name: 'PetitPotato' }
        - { repo: 'https://github.com/k4sth4/Juicy-Potato.git', name: 'Juicy-Potato' }
        - { repo: 'https://github.com/zcgonvh/EfsPotato.git', name: 'EfsPotato' }
        - { repo: 'https://github.com/zcgonvh/DCOMPotato.git', name: 'DCOMPotato' }
        - { repo: 'https://github.com/bugch3ck/SharpEfsPotato.git', name: 'SharpEfsPotato' }
        - { repo: 'https://github.com/antonioCoco/RoguePotato.git', name: 'RoguePotato'}
        - { repo: 'https://github.com/Leo4j/Invoke-ADEnum.git', name: 'Invoke-ADEnum' }
        - { repo: 'https://github.com/PowerShellMafia/PowerSploit.git', name: 'PowerSploit' }
        - { repo: 'https://github.com/ParrotSec/mimikatz.git', name: 'Mimikatz' }
        - { repo: 'https://github.com/sense-of-security/ADRecon.git', name: 'ADRecon' }
        - { repo: 'https://github.com/HarmJ0y/PowerUpSQL.git', name: 'PowerUPSQL' }
        - { repo: 'https://github.com/AlessandroZ/LaZagne.git', name: 'LaZagne' }
        - { repo: 'https://github.com/Arvanaghi/SessionGopher.git', name: 'SessionGopher' }
        - { repo: 'https://github.com/AlexisAhmed/CVE-2022-0847-DirtyPipe-Exploits.git', name: 'Dirty Pipe CVE-2022-0847' }
        - { repo: 'https://github.com/S3cur3Th1sSh1t/PowerSharpPack.git', name: 'PowerSharpPack' }
        - { repo: 'https://github.com/Ridter/noPac.git', name: 'Nopac' }
        - {repo: 'https://github.com/dievus/lnkbomb.git', name: 'lnkbomb' }
        - { repo: 'https://github.com/nidem/kerberoast.git', name: 'kerberoast' }
        - { repo: 'https://github.com/byt3bl33d3r/ItWasAllADream.git', name: 'itwasalladream_printnightmare'}
        - { repo: 'https://github.com/Kevin-Robertson/Inveigh.git', name: 'inveigh' }
        - { repo: 'https://github.com/t3l3machus/hoaxshell.git', name: 'hoaxshell' }
        - { repo: 'https://github.com/MichaelGrafnetter/DSInternals.git', name: 'DSinternals' }
        - { repo: 'http://github.com/thewover/donut.git', name: 'donut' }
        - { repo: 'https://github.com/dafthack/DomainPasswordSpray.git', name: 'DomainpasswordSpray' }
        - { repo: 'https://github.com/adrecon/ADRecon.git', name: 'ADrecon' }
      tags: windows
      ignore_errors: yes

    # Windows Compiled
    - name: Clone Windows Compiled tools to /opt/windows/compiled
      git:
        repo: "{{ item.repo }}"
        dest: "/opt/compiled/{{ item.name }}"
      loop:
        - { repo: 'https://github.com/MAWK0235/certify-compiled.git', name: 'certify' }
        - { repo: 'https://github.com/r3motecontrol/Ghostpack-CompiledBinaries.git', name: 'Ghostpack-CompiledBinaries' }
        - { repo: 'https://github.com/samratashok/nishang.git', name: 'Nishang_powershell' }
      tags: windows
      ignore_errors: yes

    # Windows Compiled Part II
    - name: Clone Windows Compiled tools to /opt/windows/compiled
      get_url:
        url: "{{ item.url }}"
        dest: "/opt/compiled/{{ item.name }}"
      loop:
        - { url: 'https://github.com/antonioCoco/RoguePotato/releases/download/1.0/RoguePotato.zip', name: 'RoguePotato.zip' }
        - { url: 'https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer32.exe', name: 'PrintSpoofer32.exe' }
        - { url: 'https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer64.exe', name: 'PrintSpoofer64.exe' }
        - { url: 'https://github.com/frohoff/ysoserial/releases/download/v0.0.6/ysoserial-all.jar', name: 'ysoserial.jar'}
        - { url: 'https://github.com/BishopFox/ysoserial-bf/releases/download/2023-12-19-01/ysoserial-0.0.6-SNAPSHOT-all.jar', name: 'ysoserial-0.0.6-SNAPSHOT-all.jar' }
        - { url: 'https://github.com/SnaffCon/Snaffler/releases/download/1.0.184/Snaffler.exe', name: 'snaffler.exe' }
        - { url: 'https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer32.exe', name: 'Printspoofer32.exe' }
        - { url: 'https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer64.exe', name: 'Printspoofer64.exe' }
        - { url: 'https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_linux_amd64', name: 'kebrute_linux_amd64'}
        - { url: 'https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_windows_amd64.exe', name: 'kerbrute_windows_amd64.exe' }
      tags: windows 
      ignore_errors: yes

    # PSPY
    - name: Clone PsPy to /opt/PSPY/
      get_url:
        url: "{{ item.url }}"
        dest: "/opt/PSPY/{{ item.filename }}"
      loop:
        - { url: 'https://github.com/DominicBreuker/pspy/releases/download/v1.2.1/pspy64', filename: 'pspy64' }
        - { url: 'https://github.com/DominicBreuker/pspy/releases/download/v1.2.1/pspy64s', filename: 'pspy64s' }
        - { url: 'https://github.com/DominicBreuker/pspy/releases/download/v1.2.1/pspy32', filename: 'pspy32' }
        - { url: 'https://github.com/DominicBreuker/pspy/releases/download/v1.2.1/pspy32s', filename: 'pspy32s' }
      tags: pspy
      ignore_errors: yes

    # Cloud
    - name: Clone cloud tools to /opt/cloud/
      git:
        repo: "{{ item.repo }}"
        dest: "/opt/cloud/{{ item.name }}"
      loop:
        - { repo: 'https://github.com/andresriancho/enumerate-iam.git', name: 'enumerate-iam' }
        - { repo: 'https://github.com/carnal0wnage/weirdAAL.git', name: 'weirdAAL' }
        - { repo: 'https://github.com/BishopFox/cloudfox.git', name: 'cloudfox' }
        - { repo: 'https://github.com/RhinoSecurityLabs/pacu.git', name: 'pacu' }
        - { repo: 'https://github.com/dagrz/aws_pwn.git', name: 'aws_pwn' }
        - { repo: 'https://github.com/nccgroup/ScoutSuite.git', name: 'scoutsuite' }
        - { repo: 'https://github.com/NetSPI/MicroBurst.git', name: 'MicroBurst' }
      tags: cloud
      ignore_errors: yes

    # Cloud Part II
    - name: Get cloud tools to /opt/cloud/
      get_url:
        url: "{{ item.url }}"
        dest: "/opt/cloud/{{ item.name }}"
      loop:
        - { url: 'https://github.com/BloodHoundAD/AzureHound/releases/download/v2.2.1/azurehound-darwin-amd64.zip', name: 'azurehound' }
      tags: cloud 
      ignore_errors: yes

    # More SDR
    - name: Clone SDRangel repository
      git:
        repo: "https://github.com/f4exb/sdrangel.git"
        dest: "/opt/rf-sdr/sdrangel"
      tags: rf-sdr
      ignore_errors: yes
    - name: Clone gr-satellites repository
      git:
        repo: "https://github.com/daniestevez/gr-satellites.git"
        dest: "/opt/rf-sdr/gr-satellites"
      tags: rf-sdr
      ignore_errors: yes

    # Docker images
    - name: Pull Docker images
      command: docker pull "{{ item }}"
      loop:
        - rustscan/rustscan:latest
        - specterops/bloodhound
        - mpepping/cyberchef

    # Sliver start/update
    - name: Ensure sliver.server is executable
      command: chmod +x /opt/c2_frameworks/sliver-server_linux /opt/c2_frameworks/sliver-client_linux
      become: yes  # Run as root if needed

    - name: Start the Sliver server
      shell: ./sliver-server_linux
      args:
        chdir: /opt/c2_frameworks  # Directory where sliver-server is located
      async: 60
      poll: 0  # Continue without waiting for task to finish
      register: sliver_server_job

    - name: Wait for Sliver server to start
      async_status:
        jid: "{{ sliver_server_job.ansible_job_id }}"
      register: sliver_server_result
      until: sliver_server_result.finished
      retries: 3
      delay: 2

    - name: Run 'update' command inside Sliver
      shell: echo 'update' | ./sliver-server_linux
      args:
        chdir: /opt/c2_frameworks
      become: yes  # Run as root if needed
      register: update_output

    - name: Display update command output
      debug:
        msg: "{{ update_output.stdout }}"

