---
- name: Gathering all Windows tools
  hosts: localhost
  become: yes  # Use sudo for this playbook
  tasks:

    # Windows tools
    - name: Install additional Windows tools via apt
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-impacket
        - evil-winrm
        - chisel
        - bloodhound
        - chisel
        - remmina
      tags: windows

          # GIT Windows Tools
    - name: Clone Windows tools repositories to /opt/windows/
      git:
        repo: "{{ item.repo }}"
        dest: "/opt/windows/{{ item.name }}"
      loop:
        - { repo: 'https://github.com/lgandx/Responder.git', name: 'Responder' }
        - { repo: 'https://github.com/ropnop/kerbrute.git', name: 'kerbrute' }
        - { repo: 'https://github.com/dirkjanm/krbrelayx.git', name: 'krbrelayx' }
        - { repo: 'https://github.com/andrew-d/static-binaries.git', name: 'static-binaries' }
        - { repo: 'https://github.com/topotam/PetitPotam.git', name: 'PetitPotam' }
        - { repo: 'https://github.com/wh0amitz/PetitPotato.git', name: 'PetitPotato' }
        - { repo: 'https://github.com/k4sth4/Juicy-Potato.git', name: 'Juicy-Potato' }
        - { repo: 'https://github.com/zcgonvh/EfsPotato.git', name: 'EfsPotato' }
        - { repo: 'https://github.com/zcgonvh/DCOMPotato.git', name: 'DCOMPotato' }
        - { repo: 'https://github.com/bugch3ck/SharpEfsPotato.git', name: 'SharpEfsPotato' }
        - { repo: 'https://github.com/antonioCoco/RoguePotato.git', name: 'RoguePotato'}
        - { repo: 'https://github.com/Leo4j/Invoke-ADEnum.git', name: 'Invoke-ADEnum' }
        - { repo: 'https://github.com/PowerShellMafia/PowerSploit.git', name: 'PowerSploit' }
        - { repo: 'https://github.com/ParrotSec/mimikatz.git', name: 'Mimikatz' }
        - { repo: 'https://github.com/sense-of-security/ADRecon.git', name: 'ADRecon' }
        - { repo: 'https://github.com/HarmJ0y/PowerUpSQL.git', name: 'PowerUPSQL' }
        - { repo: 'https://github.com/AlessandroZ/LaZagne.git', name: 'LaZagne' }
        - { repo: 'https://github.com/Arvanaghi/SessionGopher.git', name: 'SessionGopher' }
        - { repo: 'https://github.com/AlexisAhmed/CVE-2022-0847-DirtyPipe-Exploits.git', name: 'Dirty Pipe CVE-2022-0847' }
        - { repo: 'https://github.com/S3cur3Th1sSh1t/PowerSharpPack.git', name: 'PowerSharpPack' }
        - { repo: 'https://github.com/Ridter/noPac.git', name: 'Nopac' }
        - {repo: 'https://github.com/dievus/lnkbomb.git', name: 'lnkbomb' }
        - { repo: 'https://github.com/nidem/kerberoast.git', name: 'kerberoast' }
        - { repo: 'https://github.com/byt3bl33d3r/ItWasAllADream.git', name: 'itwasalladream_printnightmare'}
        - { repo: 'https://github.com/Kevin-Robertson/Inveigh.git', name: 'inveigh' }
        - { repo: 'https://github.com/t3l3machus/hoaxshell.git', name: 'hoaxshell' }
        - { repo: 'https://github.com/MichaelGrafnetter/DSInternals.git', name: 'DSinternals' }
        - { repo: 'http://github.com/thewover/donut.git', name: 'donut' }
        - { repo: 'https://github.com/dafthack/DomainPasswordSpray.git', name: 'DomainpasswordSpray' }
        - { repo: 'https://github.com/adrecon/ADRecon.git', name: 'ADrecon' }
      tags: windows
      ignore_errors: yes

    # Windows Compiled
    - name: Clone Windows Compiled tools to /opt/windows/compiled
      git:
        repo: "{{ item.repo }}"
        dest: "/opt/windows/compiled/{{ item.name }}"
      loop:
        - { repo: 'https://github.com/MAWK0235/certify-compiled.git', name: 'certify' }
        - { repo: 'https://github.com/r3motecontrol/Ghostpack-CompiledBinaries.git', name: 'Ghostpack-CompiledBinaries' }
        - { repo: 'https://github.com/samratashok/nishang.git', name: 'Nishang_powershell' }
      tags: windows
      ignore_errors: yes

    # Windows Compiled Part II
    - name: Clone Windows Compiled tools to /opt/windows/compiled
      get_url:
        url: "{{ item.url }}"
        dest: "/opt/windows/compiled/{{ item.name }}"
      loop:
        - { url: 'https://github.com/antonioCoco/RoguePotato/releases/download/1.0/RoguePotato.zip', name: 'RoguePotato.zip' }
        - { url: 'https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer32.exe', name: 'PrintSpoofer32.exe' }
        - { url: 'https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer64.exe', name: 'PrintSpoofer64.exe' }
        - { url: 'https://github.com/frohoff/ysoserial/releases/download/v0.0.6/ysoserial-all.jar', name: 'ysoserial.jar'}
        - { url: 'https://github.com/BishopFox/ysoserial-bf/releases/download/2023-12-19-01/ysoserial-0.0.6-SNAPSHOT-all.jar', name: 'ysoserial-0.0.6-SNAPSHOT-all.jar' }
        - { url: 'https://github.com/SnaffCon/Snaffler/releases/download/1.0.184/Snaffler.exe', name: 'snaffler.exe' }
        - { url: 'https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer32.exe', name: 'Printspoofer32.exe' }
        - { url: 'https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer64.exe', name: 'Printspoofer64.exe' }
        - { url: 'https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_linux_amd64', name: 'kebrute_linux_amd64'}
        - { url: 'https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_windows_amd64.exe', name: 'kerbrute_windows_amd64.exe' }
      tags: windows 
      ignore_errors: yes
